version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "REPLACE_WITH_NEW"
        LoadBalancerInfo:
          ContainerName: "strapi"
          ContainerPort: 1337