name: Strapi Deploy Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: strapi-app-libin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Debug AWS
        run: aws sts get-caller-identity

      - name: Create ECR repository if not exists
        run: |
          aws ecr describe-repositories --repository-names $ECR_REPOSITORY --region $AWS_REGION \
          || aws ecr create-repository --repository-name $ECR_REPOSITORY --region $AWS_REGION

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and Push Image
        run: |
          IMAGE_TAG=${{ github.sha }}

          docker build -t $ECR_REPOSITORY:$IMAGE_TAG ./my-strapi-app
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Register Task Definition & Deploy via CodeDeploy
        run: |
          IMAGE_TAG=${{ github.sha }}

          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

          echo "Registering new task definition..."

          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --family strapi-task \
            --network-mode awsvpc \
            --requires-compatibilities FARGATE \
            --cpu "512" \
            --memory "1024" \
            --execution-role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecs_fargate_taskRole \
            --task-role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecs_fargate_taskRole \
            --container-definitions "[{
              \"name\": \"strapi\",
              \"image\": \"$IMAGE_URI\",
              \"essential\": true,
              \"portMappings\": [{
                \"containerPort\": 1337,
                \"hostPort\": 1337
              }]
            }]" \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)

          echo "Triggering CodeDeploy..."

          aws deploy create-deployment \
            --application-name strapi-codedeploy \
            --deployment-group-name strapi-deployment-group \
            --deployment-config-name CodeDeployDefault.ECSCanary10Percent5Minutes \
            --revision "revisionType=AppSpecContent,appSpecContent={\"content\":\"{
              \\\"version\\\":1,
              \\\"Resources\\\":[{
                \\\"TargetService\\\":{
                  \\\"Type\\\":\\\"AWS::ECS::Service\\\",
                  \\\"Properties\\\":{
                    \\\"TaskDefinition\\\":\\\"$TASK_DEF_ARN\\\",
                    \\\"LoadBalancerInfo\\\":{
                      \\\"ContainerName\\\":\\\"strapi\\\",
                      \\\"ContainerPort\\\":1337
                    }
                  }
                }
              }]
            }\"}"